---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel
  # https://github.com/wix/eslint-plugin-lodash
  - lodash

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:lodash/recommended'

rules:
  no-console: 0
  single-quote: true,
  tab-width: 4,
  use-tabs: false
